language: python
python:
- '2.7'
- '3.4'
install:
- pip install tox
- pip install pex
- pip install -r requirements.txt
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')
- pex . --no-wheel -o dist/seriesmgmt$(echo $TRAVIS_PYTHON_VERSION | tr -d .).pex -e seriesmgmtsystem.main:main --platform=linux-x86_64
- tox -e docs
notifications:
  slack:
    secure: PGoIf/m17cPQAVW/8oIork4qg2uYyLPAGaZ+ral9E3E7E2NTshtnD28YoMWYflBu/W2BFot11h/tgYrcyxRNv8U/5RDezS8lMtwKroc4OxbVI86W20pwuepPsKgovbWXYkmGvsRuzqxiewA3Tqd1g+xAArLOjx3eQ+KQTxTrJHQl1UGZhR8SI3Anhdp7dhlbIUk69QCumtRGGbWJ12oUdU5jm/u0mLz7fnrnu1ytqrRXial6wQ+89WtN5egv9py5YXxXwci3ANWcqgJIUubdOIEgQIlYuwhtum3HQgumbTUE6pX1G8UHuELMaQfDVccCItfW8geaKS3P8syg9sSX3787x6RhDPGTZjaVhMTYIYSOT+aQztIVv6d+RJ53Wdnb/kdnN7T5dt9KK4c9owF5IvA9xhFZEQafJ11hj8C/PBAxadqUKc5rLT/+VKy0FoSwX/zAAIV2j4BrHf8EeyaXh7WEYALbMZofVYWkMZeJANMWP+quvGnPixHCVzlD5S86MCd+zJxXtvXrWZ1n6ts26s7FW/SjnhY8roTKFwqPFqINpIdQd07j4m+5FybV12zt4d+O48/wypLZGfBfdU040PMZbBgVsz46Km1GUUrnJrP8NHTffmktZ9Pk4PT3YeU9LSZ6JvMW0yjnDkg3pYe12W8ggbF79TCVOhJAphOmsWA=
  email:
    recipients:
    - andreas.ruppen@gmail.com
    on_success: change
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: "W8jOmiu5FdN1cEajmlEdW7E79Epts6An9BGYtJrQyfwX0/MZKgiKGvO/aY7REEPlLhEcBOmyhQJ5p0CavqcyIdU6Jm9SP2K8j5jRH2O1RAYNTCAH3t8Uv6AchDqIbYIjg5i+0oi10RLOaEbvnN09ZIm0u+lTciVRIqk54+zFUFv72KbCAtfX4LFKqZkdeou3u03NcufEP1mZd+v84ywpezvWqNnLKViV1S7kMlTQ8VqMA3r0c1l7ZaSSsirBp5ZGzziqwHpVy/wz+loVJX7VTUs3bAGrS/ZBn+VqMuflR7etMrftfKwQEgJC8jyQfr8MIYL7U6m+FpJP0DIpssqMga+JMbOmUAzNWqA5gGbUne2Ba7+QPjmW8d4dRaLwCbmUkvlA9kFaOFQTwusyyPoSM2ETcPpEWCQFc3Cwiy9f7Jn6XLfAkVI00pXaklPtZS98LE4A2EkmdXFeX3MVNR6HIU+0JzFOTjGOjOyUn0TLu+PR0wXJIyT8dbYiwplr5JKeKwNe3FMs4kQH25ImRbI+CtBDKqwnHJkuh/seg9Wkb9TucLmrR/pG1tG0Vu0BthS21pE1LiaUmTs5s4++W+HSuBqYj2+cBQK4IOeDEUmiqtRu7GFHe4bMNszbxbSYPwv02ESU1N76tvvPmQfyzgXYuh3kGoq8yAzrqHRiuS+Lu6s="
  file:
  - dist/seriesmgmt$(echo $TRAVIS_PYTHON_VERSION | tr -d .).pex
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
