language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install tox
script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')
notifications:
  slack:
    on_success: always
  email:
    recipients:
      - andreas.ruppen@gmail.com
    on_success: change
    on_failure: always
